<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Braimp.Domain\Braimp.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Notifications\Commands\CreateNotification\" />
    <Folder Include="Features\Notifications\Commands\DeleteNotification\" />
    <Folder Include="Features\Notifications\Commands\UpdateNotification\" />
    <Folder Include="Features\Notifications\Queries\GetNotificationDetails\" />
    <Folder Include="Features\Notifications\Queries\GetNotifications\" />
    <Folder Include="Features\QuizOptions\Commands\" />
    <Folder Include="Features\QuizOptions\Queries\" />
    <Folder Include="Features\QuizQuestions\Commands\" />
    <Folder Include="Features\QuizQuestions\Queries\" />
    <Folder Include="Features\Quizzes\Commands\" />
    <Folder Include="Features\Quizzes\Queries\" />
  </ItemGroup>

</Project>
